# This file is used to create a ClusterIssuer for cert-manager using Let's Encrypt.
# it defines the configuration for the ACME server, email, and the solver method.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nicolas.tahon@ecoles-epsi.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: Nginx